hello_project/hello/hello/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
)

hello_project/hello/hello_project/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'hello_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', RedirectView.as_view(url='/hello/')),
    url(r'^hello/', include('hello.urls', namespace='hello')),

    url(r'^admin/', include(admin.site.urls)),
)

hello_project/hello/hello/models.py
from django.db import models

# Create your models here.

hello_project/hello/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

from jabbalib import myhash


def index(request):
    name = 'Jabba'
    context = {
        'name': name,
        'md5': myhash.string_to_md5(name),
        'list': [2, "3", False, None, 3.14],
    }
    return render(request, 'hello/index.html', context)


#def about(request):
#    return HttpResponse("about")


def about(request):
    return render(request, 'hello/about.html')

hello_project/hello/hello/templates/hello/about.html
{% extends "hello/layout.html" %}

{% block body %}

<h1>About</h1>

<a href="{% url 'hello:index' %}">Back</a>

{% endblock body %}

hello_project/hello/hello/templates/hello/index.html
{% extends "hello/layout.html" %}
{% load jabbalib_extras %}

{% block body %}

<h1>Hello</h1>

<p>
{{ name }} in md5: {{ md5 }}
</p>

<p>
list: {{ list }}
</p>

<p>
list as JSON: {{ list|jsonify }}
</p>

<a href="{% url 'hello:about' %}">About</a>

{% endblock body %}

hello_project/hello/hello/templates/hello/layout.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
    <title>Hello Django!</title>
    <link rel="stylesheet" type="text/css" href="{% static 'hello/style.css' %}">
</head>

{% block body %}{% endblock body %}

</body>
</html>